array_horizontal_layout_threshold = 1000
array_width = 120
chain_one_line_max = 120
chain_split_single_child = true
comment_width = 120
condense_wildcard_suffixes = true
fn_call_width = 120
force_explicit_abi = false
format_strings = true
hard_tabs = true
imports_indent = "Block"
match_block_trailing_comma = true
match_pattern_separator_break_point = "Front"
max_width = 120
multiline_closure_forces_block = true
multiline_match_arm_forces_block = true
normalize_comments = true
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
single_line_if_else_max_width = 120
struct_lit_width = 120
struct_variant_width = 120
use_try_shorthand = true
where_density = "Vertical"
